- package_manager: "javascript"
  directory: /
  update_schedule: live
  default_assignees:
  - fredrikhr
  automerged_updates:
  - match:
      dependency_type:  "production"
      update_type:      "semver:minor"
  - match:
      dependency_type:  "development"
      update_type:      "all"
