on:
  workflow_dispatch:
    inputs:
      repo-name:
        type: string
        required: true
        description: ''
      description:
        type: string
        required: false
        description: ''
      disable-issues:
        type: boolean
        required: false
        default: false
        description: ''
      disable-wiki:
        type: boolean
        required: false
        default: false
        description: ''
      gitignore:
        type: string
        required: false
        default: VisualStudio
        description: ''
      license:
        type: string
        required: false
        default: MIT
        description: ''
      visibility:
        type: choice
        required: false
        default: ''
        options:
          - ''
          - public
          - private
          - internal
        description: ''

permissions:
  repository-projects: write

defaults:
  run:
    shell: pwsh

jobs:
  repo-create:
    name: Create Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Chekout ${{ github.repository }}@${{ github.ref || github.sha }}
      - uses: thnetii/gh-actions/src/gh-actions-npm@main
        with:
          arguments: |
            clean-install
            --workspace=gh-repo-create
            --omit=dev
          working-directory: .github/actions
        name: npm clean-install --workspace .github/actions/gh-repo-create --omit=dev
      - uses: ./.github/actions/gh-repo-create
        with:
          repo-name: ${{ inputs.repo-name }}
          description: ${{ inputs.description }}
          disable-issues: ${{ inputs.disable-issues }}
          disable-wiki: ${{ inputs.disable-wiki }}
          gitignore: ${{ inputs.gitignore }}
          license: ${{ inputs.license }}
          visibility: ${{ inputs.visibility }}
        name: gh repo create ${{ inputs.repo-name }}
