on:
  workflow_call:
    inputs: {}

jobs:
  workflow_call-info:
    runs-on: ubuntu-latest
    steps:
      - run: Write-Host $ENV:ACTIONS_CONTEXT_INPUTS_FROM_JSON
        name: 'GitHub actions context: inputs'
        shell: pwsh
        env:
          ACTIONS_CONTEXT_INPUTS_FROM_JSON: ${{ toJSON(inputs) }}
      - run: Write-Host $ENV:ACTIONS_CONTEXT_GITHUB_FROM_JSON
        name: 'GitHub actions context: github'
        shell: pwsh
        env:
          ACTIONS_CONTEXT_GITHUB_FROM_JSON: ${{ toJSON(github) }}
      - run: Write-Host $ENV:ACTIONS_CONTEXT_JOB_FROM_JSON
        name: 'GitHub actions context: job'
        shell: pwsh
        env:
          ACTIONS_CONTEXT_JOB_FROM_JSON: ${{ toJSON(job) }}
